const songs = [
    {
        img: "../images/songs/lovely.png",
        title: "LOVELY (WITH KHALID)",
        release: "April 19, 2018",
        album: "13 Reasons Why: Season 2",
        clip: "/sounds/lovely.mp3",
        tag: "'Lovely,' featuring Khalid, explores the struggle of facing inner pain and loneliness while striving to find hope and beauty in the midst of darkness.",
    },
    {
        img: "../images/songs/badguy.png",
        title: "BAD GUY",
        release: "March 29, 2019",
        album: "When We Fall Asleep, Where Do We Go?",
        clip: "/sounds/badguy.mp3",
        tag: "'Bad guy' playfully critiques societal stereotypes and challenges power dynamics in relationships, blending dark humor with themes of rebellion and self-awareness.",
    },
    {
        img: "../images/songs/partysover.png",
        title: "WHEN THE PARTY'S OVER",
        release: "October 17, 2018",
        album: "When We Fall Asleep, Where Do We Go?",
        clip: "/sounds/partysover.mp3",
        tag: "'When the party's over' captures the emotional aftermath of a toxic relationship, expressing feelings of heartbreak, detachment, and the struggle to let go despite lingering love.",
    },
    {
        img: "../images/songs/everything.png",
        title: "EVERYTHING I WANTED",
        release: "November 15, 2019",
        album: "When We Fall Asleep, Where Do We Go? Deluxe Edition",
        clip: "/sounds/everything.mp3",
        tag: "'Everything i wanted' explores themes of vulnerability, self-doubt, and the importance of unconditional support, as it reflects her struggle with fame and mental health, anchored by the comforting bond she shares with her brother, Finneas.",
    },
    {
        img: "../images/songs/oceaneyes.png",
        title: "OCEAN EYES",
        release: "November 18, 2016",
        album: "Don't Smile at Me",
        clip: "/sounds/oceaneyes.mp3",
        tag: "'Ocean Eyes' conveys the overwhelming emotions of love and longing, capturing the vulnerability and intensity of being mesmerized by someone’s captivating presence.",
    },
    {
        img: "../images/songs/birds.png",
        title: "BIRDS OF A FEATHER",
        release: "July 2, 2024",
        album: "Hit Me Hard and Soft",
        clip: "/sounds/birds.mp3",
        tag: "'Birds of a Feather' explores themes of connection and understanding, symbolizing a bond between individuals who share similar emotions, experiences, or struggles, emphasizing unity and mutual support.",
    },
    {
        img: "../images/songs/happier.png",
        title: "HAPPIER THAN EVER",
        release: "July 30, 2021",
        album: "Happier Than Ever",
        clip: "/sounds/happier.mp3",
        tag: "'Happier Than Ever' reflects the liberation and emotional clarity that comes from breaking free of a toxic relationship, expressing both vulnerability and empowerment.",
    },
    {
        img: "../images/songs/dontwanna.png",
        title: "IDONTWANNABEYOU ANYMORE",
        release: "July 21, 2017",
        album: "Don't Smile at Me",
        clip: "/sounds/dontwanna.mp3",
        tag: "'idontwannabeyouanymore' explores themes of self-doubt and inner struggle, reflecting a yearning to escape feelings of insecurity and self-criticism.",
    },
    {
        img: "../images/songs/madefor.png",
        title: "WHAT WAS I MADE FOR?",
        release: "July 13, 2023",
        album: "Barbie the Album",
        clip: "/sounds/madefor.mp3",
        tag: "'What Was I Made For?' explores the societal pressures and existential struggles many women face, questioning their roles and identities beyond societal expectations and traditional gender norms.",
    },
    {
        img: "../images/songs/bored.png",
        title: "BORED",
        release: "March 30, 2017",
        album: "13 Reasons Why (A Netflix Original Series Soundtrack)",
        clip: "/sounds/bored.mp3",
        tag: "'Bored' explores feelings of emotional numbness and dissatisfaction, capturing the internal struggle of longing for connection and purpose while feeling disconnected from everything around oneself.",
    },
    {
        img: "../images/songs/buryfriend.png",
        title: "BURY A FRIEND",
        release: "January 30, 2019",
        album: "When We Fall Asleep, Where Do We Go?",
        clip: "/sounds/buryfriend.mp3",
        tag: "'Bury a friend' explores themes of inner turmoil, self-doubt, and the struggle with identity, using a dark, haunting perspective to convey feelings of alienation and self-destruction.",
    },
    {
        img: "../images/songs/bellyache.png",
        title: "BELLYACHE",
        release: "February 24, 2017",
        album: "Don't Smile at Me",
        clip: "/sounds/bellyache.mp3",
        tag: "'Bellyache' explores feelings of guilt, confusion, and internal conflict, as the narrator grapples with the consequences of their actions and the emotional turmoil that follows.",
    },
    {
        img: "../images/songs/iloveyou.png",
        title: "I LOVE YOU",
        release: "March 29, 2019",
        album: "When We Fall Asleep, Where Do We Go?",
        clip: "/sounds/iloveyou.mp3",
        tag: "'I love you' explores the complex emotions of love, vulnerability, and the tension between desire for connection and the fear of losing oneself in a relationship.",
    },
    {
        img: "../images/songs/inacrown.png",
        title: "YOU SHOULD SEE ME IN A CROWN",
        release: "July 18, 2018",
        album: "When We Fall Asleep, Where Do We Go?",
        clip: "/sounds/inacrown.mp3",
        tag: "'You Should See Me in a Crown' reflects themes of self-confidence, empowerment, and defiance, as the artist embraces her own strength and dominance while challenging societal expectations and perceptions of power.",
    },
    {
        img: "../images/songs/therefore.png",
        title: "THEREFORE I AM",
        release: "November 12, 2020",
        album: "Happier Than Ever",
        clip: "/sounds/therefore.mp3",
        tag: "'Therefore I Am' expresses a defiant and confident rejection of others' expectations and judgments, emphasizing self-empowerment and embracing one's true identity without needing validation.",
    },
    {
        img: "../images/songs/wishyouwere.png",
        title: "WISH YOU WERE GAY",
        release: "March 4, 2019",
        album: "When We All Fall Asleep, Where Do We Go?",
        clip: "/sounds/wishyouwere.mp3",
        tag: "'Wish you were gay' expresses the pain and confusion of unrequited love, where the singer wishes the person she loves could have a reason, like their sexual orientation, for not reciprocating her feelings."
    },
    {
        img: "../images/songs/watch.png",
        title: "WATCH",
        release: "June 29, 2017",
        album: "Don't Smile at Me",
        clip: "/sounds/watch.mp3",
        tag: "'Watch' explores feelings of detachment and emotional numbness, reflecting on the difficulty of maintaining relationships in a world where time and personal growth seem to push people apart.",
    },
    {
        img: "../images/songs/tv.png",
        title: "TV",
        release: "July 21, 2022",
        album: "Guitar Songs",
        clip: "/sounds/tv.mp3",
        tag: "'TV' reflects the emotional disconnection and disillusionment that comes with the overwhelming presence of media, while exploring personal feelings of isolation, heartache, and the desire for genuine human connection."
    },
    {
        img: "../images/songs/goodgirls.png",
        title: "ALL THE GOOD GIRLS GO TO HELL",
        release: "September 6, 2019",
        album: "When We All Fall Asleep, Where Do We Go?",
        clip: "/sounds/goodgirls.mp3",
        tag: "'All the Good Girls Go to Hell' explores themes of environmental destruction, societal apathy, and the consequences of human negligence, using the metaphor of 'good girls' to represent those who are complicit or unaware of the looming crisis."
    },
    {
        img: "../images/songs/notime.png",
        title: "NO TIME TO DIE",
        release: "February 13, 2020",
        album: "No Time to Die: Original Motion Picture Soundtrack",
        clip: "/sounds/notime.mp3",
        tag: "'No Time to Die' explores themes of betrayal, heartbreak, and emotional vulnerability, capturing the internal conflict of facing the end of a relationship while grappling with feelings of loss and anger."
    },
];

export default songs;